// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================


#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;




   #define AUTOTB_TVIN_p  "../tv/cdatafile/c.example.autotvin_p.dat"
   #define AUTOTB_TVIN_a  "../tv/cdatafile/c.example.autotvin_a.dat"
   #define AUTOTB_TVOUT_a  "../tv/cdatafile/c.example.autotvout_a.dat"
   #define INTER_TCL  "../tv/cdatafile/ref.tcl"

   #define AUTOTB_TVOUT_PC_a  "../tv/rtldatafile/rtl.example.autotvout_a.dat"

class INTER_TCL_FILE {
    public:
//functions
        INTER_TCL_FILE(const char* name) {
            mName = name;
            p_depth = 0;
            a_depth = 0;
            trans_num =0;
        }
        ~INTER_TCL_FILE() {
            mFile.open(mName);
            if (!mFile.good() ) {
                cout<<"Failed to open file ref.tcl."<<endl;
                exit (1);
            }
            string total_list = get_depth_list();
            mFile<<"set depth_list {\n";
            mFile<<total_list; 
            mFile<<"}\n";
            mFile<<"set trans_num "<<trans_num<<endl;
            mFile.close();
        }
        string get_depth_list () {
            stringstream total_list;
            total_list<<"   {p "<< p_depth << "}\n";
            total_list<<"   {a "<< a_depth << "}\n";
            return total_list.str();
        }
        void set_num (int num , int* class_num) {
            (*class_num) = (*class_num) > num ? (*class_num) : num;
        }
    public:
//variables
        int p_depth;
        int a_depth;
        int trans_num;
    private:
        ofstream mFile;
        const char* mName;
};

#define example AESL_ORIG_DUT_example
extern void example (volatile char* p, volatile int* a);
#undef example
void example (volatile char* p, volatile int* a) {

    fstream wrapc_switch_file_token;

    wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");

    int AESL_i;

    if (wrapc_switch_file_token.good()) {

        static unsigned AESL_transaction_pc;

        string AESL_token;

        string AESL_num;

        static AESL_FILE_HANDLER aesl_fh;

        aesl_fh.read(AUTOTB_TVOUT_PC_a, AESL_token); //[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           exit(1);

        }

        aesl_fh.read(AUTOTB_TVOUT_PC_a, AESL_num); //transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            aesl_fh.read(AUTOTB_TVOUT_PC_a, AESL_token); //data

            sc_bv<32> *a_pc_buffer = new sc_bv<32>[50];

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'a', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'a', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    a_pc_buffer[i] = AESL_token.c_str();

                    i++;

                }

                aesl_fh.read(AUTOTB_TVOUT_PC_a, AESL_token); //data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_a)) {

                   exit(1);

                }

            }

            if (i > 0) {

                sc_lv<32> *a_lv0_0_49_1 = new sc_lv<32>[50];

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= 49 ; i_0+= 1) {

                    if(&(a[0]) != 0) {

                       a_lv0_0_49_1[0 + AESL_i].range(31, 0) = sc_bv<32>(a_pc_buffer[0 + AESL_i].range(31, 0));

                    }

                    AESL_i++;

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= 49 ; i_0+= 1) {

                    if(&(a[0]) != 0) {

                       a[i_0] = (a_lv0_0_49_1[0 + AESL_i]).to_uint64();

                    }

                    AESL_i++;

                }

                }

            delete [] a_pc_buffer;

        }

        AESL_transaction_pc ++ ;

    } else {

        static unsigned AESL_transaction;

        static AESL_FILE_HANDLER aesl_fh;

        char* tvin_p = new char[50];

        char* tvin_a = new char[50];

        char* tvout_a = new char[50];

        static INTER_TCL_FILE tcl_file(INTER_TCL);


        int leading_zero;

        sprintf(tvin_p, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_p, tvin_p);

        sc_bv<8> *p_tvin_wrapc_buffer = new sc_bv<8>[100];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 99 ; i_0+= 1) {

        sc_lv<8> p_tmp_mem; 

            if(&(p[0]) != 0) {

            p_tmp_mem = p[i_0];

               p_tvin_wrapc_buffer[0 + AESL_i].range(7, 0) = p_tmp_mem.range(7, 0 ) ;

            }

            AESL_i++;

        }

        for (int i = 0; i < 100 ; i++) {

            sprintf(tvin_p, "%s\n", (p_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_p, tvin_p);

        }

        tcl_file.set_num(100,&tcl_file.p_depth);

        sprintf(tvin_p, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_p, tvin_p);

        delete [] p_tvin_wrapc_buffer;

        sprintf(tvin_a, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVIN_a, tvin_a);

        sc_bv<32> *a_tvin_wrapc_buffer = new sc_bv<32>[50];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 49 ; i_0+= 1) {

        sc_lv<32> a_tmp_mem; 

            if(&(a[0]) != 0) {

            a_tmp_mem = a[i_0];

               a_tvin_wrapc_buffer[0 + AESL_i].range(31, 0) = a_tmp_mem.range(31, 0 ) ;

            }

            AESL_i++;

        }

        for (int i = 0; i < 50 ; i++) {

            sprintf(tvin_a, "%s\n", (a_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVIN_a, tvin_a);

        }

        tcl_file.set_num(50,&tcl_file.a_depth);

        sprintf(tvin_a, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVIN_a, tvin_a);

        delete [] a_tvin_wrapc_buffer;

        AESL_ORIG_DUT_example(p,a);

        sprintf(tvout_a, "[[transaction]] %d\n", AESL_transaction);

        aesl_fh.write(AUTOTB_TVOUT_a, tvout_a);

        sc_bv<32> *a_tvout_wrapc_buffer = new sc_bv<32>[50];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 49 ; i_0+= 1) {

        sc_lv<32> a_tmp_mem; 

            if(&(a[0]) != 0) {

            a_tmp_mem = a[i_0];

               a_tvout_wrapc_buffer[0 + AESL_i].range(31, 0) = a_tmp_mem.range(31, 0 ) ;

            }

            AESL_i++;

        }

        for (int i = 0; i < 50 ; i++) {

            sprintf(tvout_a, "%s\n", (a_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

            aesl_fh.write(AUTOTB_TVOUT_a, tvout_a);

        }

        tcl_file.set_num(50,&tcl_file.a_depth);

        sprintf(tvout_a, "[[/transaction]] \n");

        aesl_fh.write(AUTOTB_TVOUT_a, tvout_a);

        delete [] a_tvout_wrapc_buffer;

        delete [] tvin_p;

        delete [] tvin_a;

        delete [] tvout_a;

        AESL_transaction++;

        tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

    }
}


