// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xafaprocess_hw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAfaprocess_hw_CfgInitialize(XAfaprocess_hw *InstancePtr, XAfaprocess_hw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Interface_axilite_slave_BaseAddress = ConfigPtr->Interface_axilite_slave_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAfaprocess_hw_Start(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL) & 0x80;
    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAfaprocess_hw_IsDone(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAfaprocess_hw_IsIdle(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAfaprocess_hw_IsReady(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAfaprocess_hw_EnableAutoRestart(XAfaprocess_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL, 0x80);
}

void XAfaprocess_hw_DisableAutoRestart(XAfaprocess_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_CTRL, 0);
}

u32 XAfaprocess_hw_Get_return(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_AP_RETURN);
    return Data;
}
void XAfaprocess_hw_Set_baseAddr(XAfaprocess_hw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_BASEADDR_DATA, Data);
}

u32 XAfaprocess_hw_Get_baseAddr(XAfaprocess_hw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_BASEADDR_DATA);
    return Data;
}

void XAfaprocess_hw_InterruptGlobalEnable(XAfaprocess_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_GIE, 1);
}

void XAfaprocess_hw_InterruptGlobalDisable(XAfaprocess_hw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_GIE, 0);
}

void XAfaprocess_hw_InterruptEnable(XAfaprocess_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_IER);
    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_IER, Register | Mask);
}

void XAfaprocess_hw_InterruptDisable(XAfaprocess_hw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_IER);
    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_IER, Register & (~Mask));
}

void XAfaprocess_hw_InterruptClear(XAfaprocess_hw *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAfaprocess_hw_WriteReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_ISR, Mask);
}

u32 XAfaprocess_hw_InterruptGetEnabled(XAfaprocess_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_IER);
}

u32 XAfaprocess_hw_InterruptGetStatus(XAfaprocess_hw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAfaprocess_hw_ReadReg(InstancePtr->Interface_axilite_slave_BaseAddress, XAFAPROCESS_HW_INTERFACE_AXILITE_SLAVE_ADDR_ISR);
}

