#pragma line 1 "proj_axi_master/src/AFAProcessFunction.cpp" ::: 0
#pragma line 1 "proj_axi_master/src/AFAProcessFunction.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 152 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 13
#pragma line 145 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 66
#pragma line 401 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 196
#pragma line 9 "<command line>" 2 ::: 199
#pragma line 1 "<built-in>" 2 ::: 200
#pragma line 1 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 201
#pragma line 1 "proj_axi_master/src/../../include/AFATypes.h" 1 ::: 203
#pragma line 3 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 220
#pragma line 1 "proj_axi_master/src/../../include/AFADefines.h" 1 ::: 221
#pragma line 4 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 226
#pragma line 1 "proj_axi_master/src/../../include/AFAProcessFunction.h" 1 ::: 227
#pragma line 5 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 245
#pragma line 1 "proj_axi_master/src/../../include/AFASpectra.h" 1 ::: 246
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 250
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 286
#pragma line 5 "proj_axi_master/src/../../include/AFASpectra.h" 2 ::: 289
#pragma line 1 "proj_axi_master/src/../../include/AFASpectra.h" 1 ::: 292
#pragma line 8 "proj_axi_master/src/../../include/AFASpectra.h" 2 ::: 293
#pragma line 426 "proj_axi_master/src/../../include/AFASpectra.h" ::: 677
#pragma line 6 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 689
#pragma line 1 "proj_axi_master/src/../../include/AFAProcessing.h" 1 ::: 690
#pragma line 1 "proj_axi_master/src/../../include/AFANetworkSettings.h" 1 ::: 695
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 719
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 744
#pragma line 24 "proj_axi_master/src/../../include/AFANetworkSettings.h" 2 ::: 747
#pragma line 5 "proj_axi_master/src/../../include/AFAProcessing.h" 2 ::: 793
#pragma line 1 "proj_axi_master/src/../../include/AFARandom.h" 1 ::: 795
#pragma line 6 "proj_axi_master/src/../../include/AFAProcessing.h" 2 ::: 851
#pragma line 7 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 947
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 949
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 959
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 970
#pragma line 18 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 976
#pragma line 62 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 990
#pragma line 10 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 997
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1001
#pragma line 147 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1004
#pragma line 225 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1008
#pragma line 247 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1010
#pragma line 277 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1012
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 1013
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 1027
#pragma line 674 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1033
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 1034
#pragma line 674 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 1035
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 1037
#pragma line 675 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 1038
#pragma line 13 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 1039
#pragma line 46 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 1059
#pragma line 99 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 1061
#pragma line 277 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 1066
#pragma line 316 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1070
#pragma line 370 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1076
#pragma line 380 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1078
#pragma line 392 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1080
#pragma line 405 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1082
#pragma line 418 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1084
#pragma line 436 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1086
#pragma line 456 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1089
#pragma line 518 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1109
#pragma line 605 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 1123
#pragma line 9 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1187
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_push.h" 1 3 ::: 1190
#pragma line 11 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1198
#pragma line 26 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1205
#pragma line 84 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1217
#pragma line 120 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1236
#pragma line 157 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1238
#pragma line 312 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1384
#pragma line 330 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1392
#pragma line 373 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1428
#pragma line 417 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1463
#pragma line 475 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 3 ::: 1493
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 1 3 ::: 1529
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 1 3 ::: 1539
#pragma line 9 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdio_s.h" 2 3 ::: 1545
#pragma line 509 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1546
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw_print_pop.h" 1 3 ::: 1549
#pragma line 511 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdio.h" 2 3 ::: 1557
#pragma line 9 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 1558
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 1559
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 1569
#pragma line 9 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 1575
#pragma line 36 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 3 ::: 1580
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 1 3 ::: 1721
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 1 3 ::: 1731
#pragma line 9 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/string_s.h" 2 3 ::: 1737
#pragma line 175 "C:/Xilinx/Vivado_HLS/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\string.h" 2 3 ::: 1738
#pragma line 10 "proj_axi_master/src/AFAProcessFunction.cpp" 2 ::: 1739
