// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XAFAPROCESS_HW_H
#define XAFAPROCESS_HW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xafaprocess_hw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Interface_axilite_slave_BaseAddress;
} XAfaprocess_hw_Config;
#endif

typedef struct {
    u32 Interface_axilite_slave_BaseAddress;
    u32 IsReady;
} XAfaprocess_hw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAfaprocess_hw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAfaprocess_hw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAfaprocess_hw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAfaprocess_hw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAfaprocess_hw_Initialize(XAfaprocess_hw *InstancePtr, u16 DeviceId);
XAfaprocess_hw_Config* XAfaprocess_hw_LookupConfig(u16 DeviceId);
int XAfaprocess_hw_CfgInitialize(XAfaprocess_hw *InstancePtr, XAfaprocess_hw_Config *ConfigPtr);
#else
int XAfaprocess_hw_Initialize(XAfaprocess_hw *InstancePtr, const char* InstanceName);
int XAfaprocess_hw_Release(XAfaprocess_hw *InstancePtr);
#endif

void XAfaprocess_hw_Start(XAfaprocess_hw *InstancePtr);
u32 XAfaprocess_hw_IsDone(XAfaprocess_hw *InstancePtr);
u32 XAfaprocess_hw_IsIdle(XAfaprocess_hw *InstancePtr);
u32 XAfaprocess_hw_IsReady(XAfaprocess_hw *InstancePtr);
void XAfaprocess_hw_EnableAutoRestart(XAfaprocess_hw *InstancePtr);
void XAfaprocess_hw_DisableAutoRestart(XAfaprocess_hw *InstancePtr);
u32 XAfaprocess_hw_Get_return(XAfaprocess_hw *InstancePtr);

void XAfaprocess_hw_Set_baseAddr(XAfaprocess_hw *InstancePtr, u32 Data);
u32 XAfaprocess_hw_Get_baseAddr(XAfaprocess_hw *InstancePtr);

void XAfaprocess_hw_InterruptGlobalEnable(XAfaprocess_hw *InstancePtr);
void XAfaprocess_hw_InterruptGlobalDisable(XAfaprocess_hw *InstancePtr);
void XAfaprocess_hw_InterruptEnable(XAfaprocess_hw *InstancePtr, u32 Mask);
void XAfaprocess_hw_InterruptDisable(XAfaprocess_hw *InstancePtr, u32 Mask);
void XAfaprocess_hw_InterruptClear(XAfaprocess_hw *InstancePtr, u32 Mask);
u32 XAfaprocess_hw_InterruptGetEnabled(XAfaprocess_hw *InstancePtr);
u32 XAfaprocess_hw_InterruptGetStatus(XAfaprocess_hw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
