// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xafaprocess_hw.h"

extern XAfaprocess_hw_Config XAfaprocess_hw_ConfigTable[];

XAfaprocess_hw_Config *XAfaprocess_hw_LookupConfig(u16 DeviceId) {
	XAfaprocess_hw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XAFAPROCESS_HW_NUM_INSTANCES; Index++) {
		if (XAfaprocess_hw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAfaprocess_hw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAfaprocess_hw_Initialize(XAfaprocess_hw *InstancePtr, u16 DeviceId) {
	XAfaprocess_hw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAfaprocess_hw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAfaprocess_hw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

